fix: baseurl and major version check for versions

diff --git a/.github/workflows/untp-data-models-publish.yml b/.github/workflows/untp-data-models-publish.yml
--- a/.github/workflows/untp-data-models-publish.yml
+++ b/.github/workflows/untp-data-models-publish.yml
@@ -13,6 +13,10 @@ on:
         required: false
         type: boolean
         default: false
+      major-version:
+        required: false
+        type: number
+        default: 0
     
 env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -87,9 +91,12 @@ jobs:
     - id: set-env
       name: output a baseurl for the release
       run: |
-        baseurl=$(echo "${{ env.prefix }}/${{ env.version }}" | sed -r 's/[-]+/\//g')
+        baseurl=$(echo "${{ env.prefix }}" | sed -r 's/[-]+/\//g')
         if [[ "${{ env.version}}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
           major_version=$(echo "${{ env.version }}" | sed 's/^v\([0-9]*\)\..*/\1/')
+          if [[ "$major_version" != "${{ inputs.major-version}}" ]]; then
+            echo -e "Error: major version mismatch, update input major versio" && exit 1 
+          fi
         else
           major_version="${{ env.version}}"
         fi
@@ -152,7 +159,7 @@ jobs:
     - working-directory: vocabulary-outputs
       if: ${{ !env.skip_data_model }}
       run: |
-        jq '(.majors[] | select (.major == 0).log) |= map(select(.version != "${{env.version}}"))' versions.json > versions_tmp.json
+        jq '(.majors[] | select (.major == ${{ inputs.major-version }}).log) |= map(select(.version != "${{env.version}}"))' versions.json > versions_tmp.json
         
         jq --arg version_date "$(date +'%Y-%m-%d')" \
           --argjson schemas $(find ./_artefacts -maxdepth 1 -name "*schema-${{env.version}}.json" -printf '%f\n' | jq -R -c -s 'split("\n")[:-1]') \
