feat: add untp jargon release workflow

diff --git a/.github/workflows/untp-jargon-release.yml b/.github/workflows/untp-jargon-release.yml
--- a/.github/workflows/untp-jargon-release.yml
+++ b/.github/workflows/untp-jargon-release.yml
@@ -107,7 +107,7 @@ jobs:
           git add .          
           git commit -m "feat: update ${{ github.event.client_payload.domain.name }} data model with Jargon release ${{ env.version }}" || echo -e "nothing to commit"
           
-          git push origin feature/jargon-sync-${{ env.version }}
+          git push origin feature/jargon-sync-${{ env.version }} || echo -e "Warning: feature/jargon-sync-${{ env.version }} failed"
           prs=$(gh pr list \
               --head 'feature/jargon-sync-${{ env.version }}' \
               --base 'data-models-staging' \
@@ -118,9 +118,11 @@ jobs:
             pr_title='feat: update data models with Jargon release ${{ env.version }}'
             gh pr create --title "$pr_title" --base data-models-staging --body "update ${{ github.event.client_payload.domain.name }} data model with Jargon release ${{ env.version }}"
           else
-            gh pr edit --body "$(cat <<EOF
+
+            cat > pr_body.md <<EOF
             echo $prs | jq -r '.[].body'
             echo 'update ${{ github.event.client_payload.domain.name }} data model with Jargon release ${{ env.version }}'
             EOF
-            )"
+
+            gh pr edit --body-file pr_body.md
           fi
