fix: fail workflow if vocab processing had any errors

diff --git a/.github/workflows/untp-data-models-prerelease.yml b/.github/workflows/untp-data-models-prerelease.yml
--- a/.github/workflows/untp-data-models-prerelease.yml
+++ b/.github/workflows/untp-data-models-prerelease.yml
@@ -124,7 +124,7 @@ jobs:
     - working-directory: vocabulary-outputs
       run: |
         java -jar ${{ env.utility_jar }} -m "md" -d "./" -i ${{ env.prefix }}.jsonld && cat out.md || \
-          (cat err.md && echo  "::error title=Failed to process ${{ env.prefix }}.jsonld::check logs for details")
+          (cat err.md && echo  "::error title=Failed to process ${{ env.prefix }}.jsonld::check logs for details" && exit 1)
     - working-directory: vocabulary-outputs
       run: mv versions.json _data/
     - working-directory: vocabulary-outputs
